{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "The PKCS#7 parser in OpenVPN 3 Core Library versions through 3.8.3 did not properly validate the parsed data, which would result in the application crashing."
    },
    {
      "lang": "es",
      "value": "El analizador PKCS#7 en las versiones de OpenVPN 3 Core Library hasta 3.8.3 no validó correctamente los datos analizados, lo que provocaría que la aplicación fallara."
    }
  ],
  "id": "CVE-2023-6247",
  "lastModified": "2024-11-21T08:43:27.387",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 6.5,
          "baseSeverity": "MEDIUM",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "privilegesRequired": "LOW",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 2.8,
        "impactScore": 3.6,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-02-29T01:42:34.380",
  "references": [
    {
      "source": "security@openvpn.net",
      "url": "https://community.openvpn.net/openvpn/wiki/CVE-2023-6247"
    },
    {
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "url": "https://community.openvpn.net/openvpn/wiki/CVE-2023-6247"
    }
  ],
  "sourceIdentifier": "security@openvpn.net",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-476"
        }
      ],
      "source": "security@openvpn.net",
      "type": "Secondary"
    }
  ]
}