{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue in radare2 v5.8.0 through v5.9.4 allows a local attacker to cause a denial of service via the __bf_div function."
    },
    {
      "lang": "es",
      "value": "Un problema en radare2 v5.8.0 a v5.9.4 permite que un atacante local provoque una denegación de servicio a través de la función __bf_div."
    }
  ],
  "id": "CVE-2024-48241",
  "lastModified": "2024-11-01T12:57:03.417",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "LOCAL",
          "availabilityImpact": "HIGH",
          "baseScore": 5.5,
          "baseSeverity": "MEDIUM",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "privilegesRequired": "LOW",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 1.8,
        "impactScore": 3.6,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-10-30T18:15:07.490",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/St-Andrews-Bug-Busters/Vuln_info/blob/main/radare2/CVE-2024-48241.md"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/radareorg/radare2/issues/23317"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/radareorg/radare2/pull/23318"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-787"
        }
      ],
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary"
    }
  ]
}