{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup, when an Oracle database is used, is subject to SQL injection if untrusted data is used as an lhs value. (Applications that use the jsonfield.has_key lookup via __ are unaffected.)"
    },
    {
      "lang": "es",
      "value": "Se descubrió un problema en Django 5.1 anterior a 5.1.4, 5.0 anterior a 5.0.10 y 4.2 anterior a 4.2.17. El uso directo de la búsqueda django.db.models.fields.json.HasKey, cuando se utiliza una base de datos Oracle, está sujeto a inyección SQL si se utilizan datos no confiables como valor de lhs. (Las aplicaciones que utilizan la búsqueda jsonfield.has_key mediante __ no se ven afectadas)."
    }
  ],
  "id": "CVE-2024-53908",
  "lastModified": "2024-12-06T17:15:12.350",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 9.8,
          "baseSeverity": "CRITICAL",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "HIGH",
          "privilegesRequired": "NONE",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 5.9,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-12-06T12:15:18.583",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "https://docs.djangoproject.com/en/dev/releases/security/"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://groups.google.com/g/django-announce"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://www.openwall.com/lists/oss-security/2024/12/04/3"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-89"
        }
      ],
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary"
    }
  ]
}