{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files."
    },
    {
      "lang": "es",
      "value": "Al analizar ciertos archivos PLY malformados, la versión 1.14.1 de PCL se bloquea debido a una excepción std::out_of_range no detectada en PCLPointCloud2::at. Este problema podría aprovecharse para provocar un ataque de denegación de servicio (DoS) al procesar archivos PLY que no son de confianza."
    }
  ],
  "id": "CVE-2024-53432",
  "lastModified": "2024-12-04T16:15:26.240",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 7.5,
          "baseSeverity": "HIGH",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "privilegesRequired": "NONE",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 3.6,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-11-21T18:15:14.420",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/PointCloudLibrary/pcl/issues/6162"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-754"
        }
      ],
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary"
    }
  ]
}